import Head from 'next/head';

const Books = () => {
    return (
        <>
            <Head>
                <title>BookSeller | Books</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>books page</h1>;
        </>
    );
};
export default Books;
