import { Box, Button, FormControl, InputAdornment, TextField, Typography } from '@mui/material';
import PasswordIcon from '@mui/icons-material/Password';
import AlternateEmailIcon from '@mui/icons-material/AlternateEmail';
import Head from 'next/head';
import { useState } from 'react';
import Link from 'next/link';

const LogIn = () => {
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    const handleChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
        setEmail(event.target.value);
    };
    const handleChangePassword = (event: React.ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value);
    };
    return (
        <>
            <Head>
                <title>BookSeller | Log in</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography
                variant="h4"
                style={{ textAlign: 'center', width: 300, padding: 10, margin: '0 auto' }}
            >
                Log in
            </Typography>
            <Box style={{ width: 600, margin: '0 auto', textAlign: 'center' }}>
                <FormControl>
                    <TextField
                        label="Email"
                        value={email}
                        onChange={handleChangeEmail}
                        id="outlined-start-adornment"
                        sx={{ m: 1, width: '500px' }}
                        InputProps={{
                            endAdornment: (
                                <InputAdornment position="start">
                                    <AlternateEmailIcon />
                                </InputAdornment>
                            ),
                        }}
                    />
                </FormControl>
                <FormControl>
                    <TextField
                        label="Password"
                        type="password"
                        value={password}
                        sx={{ m: 1, width: '500px' }}
                        onChange={handleChangePassword}
                        InputProps={{
                            endAdornment: (
                                <InputAdornment position="start">
                                    <PasswordIcon />
                                </InputAdornment>
                            ),
                        }}
                    />
                </FormControl>
                <Button variant="contained" style={{ width: '500px', padding: '16px' }} sx={{ m: 1 }}>
                    Log in
                </Button>
                <Link href="/reset"><p>Forgot password?</p></Link>
            </Box>
        </>
    );
};
export default LogIn;
