import { Box, FormControl, InputAdornment, TextField, Typography } from '@mui/material';
import AlternateEmailIcon from '@mui/icons-material/AlternateEmail';
import Head from 'next/head';
import React, { useState } from 'react';
import CustomButton from '../components/CustomButton';

const Reset = () => {
    const [email, setEmail] = useState<string>('');

    const handleChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
        setEmail(event.target.value);
    };
    return (
        <>
            <Head>
                <title>BookSeller | Reset</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography
                variant="h4"
                style={{
                    textAlign: 'center',
                    width: 300,
                    padding: 10,
                    margin: '0 auto',
                }}
            >
                Reset password
            </Typography>
            <Box style={{ width: 600, margin: '0 auto', textAlign: 'center' }}>
                <FormControl>
                    <TextField
                        label="Email"
                        value={email}
                        onChange={handleChangeEmail}
                        id="outlined-start-adornment"
                        sx={{ m: 1, width: '500px' }}
                        InputProps={{
                            endAdornment: (
                                <InputAdornment position="start">
                                    <AlternateEmailIcon />
                                </InputAdornment>
                            ),
                        }}
                    />
                </FormControl>
                <CustomButton>Reset password</CustomButton>
            </Box>
        </>
    );
};
export default Reset;
