import Head from 'next/head';

const Sell = () => {
    return (
        <>
            <Head>
                <title>BookSeller | Sell</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>sell page</h1>;
        </>
    );
};
export default Sell;
